version: '3.7'
services:
  dev-node  :
    container_name: react-quick-start-dev
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    volumes:
      - .:/var/www/app
    ports:
      - '3010:3010'
    environment:
      - CHOKIDAR_USEPOLLING=true
  prod-nginx:
    container_name: react-quick-start-prod
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    ports:
      - "3030:80"
    volumes:
      - ./docker/prod/nginx.conf:/etc/nginx/nginx.conf:ro
networks:
  prod:
    driver: bridge